Update FRBs
astroclubiitk/wiki pull request #12
Opened 2024-09-14 20:50 UTC by weird-polaroid

2024-09-15 03:48 UTC, tanish-singla requested changes

2024-09-15 03:48 UTC, tanish-singla commented on theory/energetic sources/GRBs.md
> +>If a [Gamma Ray Burst](#gamma-ray-bursts-grbs) directed towards us happens in the Milky Way, it will lead to the extintion of life on Earth.
Correct spellings of extinction

2024-09-15 06:16 UTC, Jadit19 requested changes

2024-09-15 06:16 UTC, Jadit19 commented on theory/energetic sources/FRBs.md
> +
Please format

2024-09-25 18:29 UTC, Jadit19 approved these changes

2024-09-25 18:33 UTC, merged